/**
 * @fileoverview Shared TypeScript interfaces for session and feedback data
 *
 * These types are used across the application for type safety and consistency:
 * - Session: Base session information (ID, timestamps)
 * - Feedback: Audience questions/feedback structure
 *
 * Usage:
 * - API routes for validation and response typing
 * - sessionStore for internal data structures
 * - Client components for prop typing
 */

/**
 * Represents a presentation session with timing information.
 *
 * Sessions are created via /api/sessions/create and stored in sessionStore.
 * They expire after 4 hours and are automatically cleaned up.
 *
 * @example
 * const session: Session = {
 *   id: "a4Bc7qZ1",
 *   createdAt: "2025-01-15T10:00:00.000Z",
 *   expiresAt: "2025-01-15T14:00:00.000Z"  // 4 hours later
 * };
 */
export interface Session {
  /** Unique 8-character session identifier generated by nanoid */
  id: string;
  /** ISO 8601 timestamp of session creation */
  createdAt: string;
  /** ISO 8601 timestamp when session expires (createdAt + 4 hours) */
  expiresAt: string;
}

/**
 * Represents a piece of audience feedback or question.
 *
 * Submitted via /api/sessions/[sessionId]/feedback and stored in sessionStore.
 * Pushed to presenter in real-time via Server-Sent Events.
 *
 * @example
 * const feedback: Feedback = {
 *   id: "xyz789",
 *   sessionId: "a4Bc7qZ1",
 *   text: "What about edge cases?",
 *   timestamp: "2025-01-15T10:15:30.000Z"
 * };
 */
export interface Feedback {
  /** Unique feedback identifier generated by nanoid(8) */
  id: string;
  /** Session ID this feedback belongs to */
  sessionId: string;
  /** Feedback/question text from audience member */
  text: string;
  /** ISO 8601 timestamp of feedback submission */
  timestamp: string;
}
